light / dark mode toggle feature
uoftblueprint/the-period-purse-2023 pull request #179
Opened 2023-07-23 23:29 UTC by kevinle623

https://github.com/uoftblueprint/the-period-purse-2023/assets/74465053/8857a86e-74e7-4ee6-a1dc-e21206e4ede7

2023-07-24 02:51 UTC, leowrites commented
In LoggingOptionsPopup, you should be able to update the color for the overlay when clicking on + in calendar

2023-07-24 02:59 UTC, kevinle623 commented
> In LoggingOptionsPopup, you should be able to update the color for the overlay when clicking on + in calendar

Nice catch, I added it

2023-07-24 02:59 UTC, leowrites requested changes

2023-07-24 02:59 UTC, leowrites commented on app/src/main/java/com/tpp/theperiodpurse/ui/setting/SettingScreenLayout.kt
> +                tint = appViewModel.colorPalette.MainFontColor,
The asset for icon in here should be dark as well

2023-07-24 02:59 UTC, leowrites commented on app/src/main/java/com/tpp/theperiodpurse/ui/legal/TermsScreen.kt
> +fun TermsScreen(navController: NavHostController, appViewModel: AppViewModel) {
In dark mode the text in here cannot be seen, it's black text on dark background. I think composables in legal/CommonComponent needs to be updated and that should fix PrivacyScreen as well

2023-07-24 02:59 UTC, leowrites commented on app/src/main/java/com/tpp/theperiodpurse/ui/symptomlog/LogScreen.kt
> +private fun LogScreenTopBarContent(navController: NavController, date: LocalDate, appViewModel: AppViewModel) {
The background color is too light compared to the design. It should be 0xFFA1A2A6

2023-07-24 02:59 UTC, leowrites commented on app/src/main/java/com/tpp/theperiodpurse/ui/symptomlog/ExercisePrompt.kt
> +fun ExercisePrompt(logViewModel: LogViewModel, appViewModel: AppViewModel) {
The textbox cannot be seen in darkmode

2023-07-24 02:59 UTC, leowrites commented on app/src/main/java/com/tpp/theperiodpurse/ui/symptomlog/NotesPrompt.kt
> +fun NotesPrompt(logViewModel: LogViewModel, appViewModel: AppViewModel) {
The textbox cannot be seen in darkmode

2023-07-24 02:59 UTC, leowrites commented on app/src/main/java/com/tpp/theperiodpurse/ui/symptomlog/SleepPrompt.kt
> +fun SleepPrompt(logViewModel: LogViewModel, appViewModel: AppViewModel) {
The textbox cannot be seen in darkmode

2023-07-24 02:59 UTC, leowrites commented on app/src/main/java/com/tpp/theperiodpurse/ui/setting/SettingScreenNavigation.kt
> +                        ResetDatabase(
Can these just be one if statement?

2023-07-24 02:59 UTC, leowrites commented on app/src/main/java/com/tpp/theperiodpurse/ui/setting/SettingScreenNavigation.kt
> +                        ),
If we are passing in appViewModel to SettingAppBar already, there is no need to pass in color

2023-07-24 02:59 UTC, leowrites commented on app/src/main/java/com/tpp/theperiodpurse/ui/component/CommonComponent.kt
> +            .background(color = appViewModel.colorPalette.CalendarDayColor)
The color in here should be darker (similar to black)

2023-07-24 02:59 UTC, leowrites commented on app/src/main/java/com/tpp/theperiodpurse/ui/education/EducationHomeScreen.kt
> +fun PeriodProducts(navController: NavHostController, it: Product, appViewModel: AppViewModel) {
background color for the card should be transparent in darkmode

2023-07-25 17:29 UTC, leowrites commented
Need verification on database and backup due to database change. Need to test migration

2023-07-25 19:28 UTC, leowrites approved these changes

2023-07-25 19:28 UTC, merged